### ISSUE TITLE
Wrong rounding for some numbers ending with ,99

### ISSUE THREAD

**Issue by louis123562** [NickKaramoff/pretty-money#10]
Hey Nick,

when using a value with 99 cents, it rounds it to 98 cents - not so cool.

<img width="686" alt="grafik" src="https://user-images.githubusercontent.com/36068395/114078739-96b0db80-98a9-11eb-96ce-ec6bcc1cf585.png">

Maybe you can check this?

Thank you :)

**Comment by kytta** [comment]
Wow, that's weird

It happens starting with 64,99 and up until 80,99... I'll try to debug this this weekend

**Comment by kytta** [comment]
![image](https://user-images.githubusercontent.com/6566248/114098373-8c9ad700-98c1-11eb-9b8b-db32bce271d6.png)

Oh, I see... 😅 

I guess it's time for a different algorithm...

**Comment by louis123562** [comment]
No hurry :)

**Comment by kytta** [comment]
I'm sorry, Louis, but this project is now archived; I will not maintain it any further. Use [`Number.prototype.toLocaleString()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString); it works correctly starting with Node 14, is built-in, and has no bugs.
