### ISSUE TITLE
Parse and normalize various input formats

### ISSUE THREAD

**Issue by louis123562** [NickKaramoff/pretty-money#7]
Hey Nick,

is it possible to extend your script to parse input values like

156.456

<img width="686" alt="grafik" src="https://user-images.githubusercontent.com/36068395/113945963-b394d280-9807-11eb-85e1-d6663daeaca9.png">

or 156.456,47

<img width="686" alt="grafik" src="https://user-images.githubusercontent.com/36068395/113945999-c3141b80-9807-11eb-976a-fdde3b9e10d5.png">

or is there a already a way to specify the input format?

You can also reach me via Discord: louis12356#6260

Thanks in advance, Louis :)

**Comment by louis123562** [comment]
Seems to work at least when i cut out the .

<img width="686" alt="grafik" src="https://user-images.githubusercontent.com/36068395/113946225-28680c80-9808-11eb-98fe-dfdc38660e95.png">

**Comment by kytta** [comment]
Moin Louis!

The field on the website is not the best representation for how the library works 😅 You see, the "Amount" field has the `type="number"`, which means that the formatting is controlled by the browser.  The browser supports only either comma or period as a _single_ non-digit, used as decimal delimiter.

In code, however, the casting to `Number` is used; that is, the number has to be in "programmer" format — no thousands delimiters, period as a decimal delimiter. Supplying `"1,234.00"` or `"45,6"` to the function will result in `NaN`

I don't know if I am going to implement better parsing in pretty-money. After all, it's not a validation/normalization library, it's a formatting library; like `strftime`, it already expects a valid type on the input. I'll leave the issue open for now

**Comment by louis123562** [comment]
Moin Nick,

okay, thank you for this detailed information :)

**Comment by kytta** [comment]
This project is now archived; I will not maintain it any further. Use [`Number.prototype.toLocaleString()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString); it works correctly starting with Node 14, is built-in, and has no bugs.
